####################
# A docker compose config for HashBrown CMS
#
# For this to work, please create a database.cfg file in the /config/ directory
# The contents of the file should look like this: { "url": "mongodb" }
####################

version: "3.4"

volumes:
    v-hashbrown-mongodb: ~
    v-hashbrown-storage: ~

networks:
    n-hashbrown: ~
    
services:
    node:
        image: node:alpine
        ports:
            - "8080:8080"
        depends_on:
            - mongodb
        networks:
            - n-hashbrown
        restart: unless-stopped
        command: "node /opt/hashbrown-cms"
        environment:
            - MONGODB_HOST=mongodb
        volumes:
            - "./:/opt/hashbrown-cms"
            - "v-hashbrown-storage:/opt/hashbrown-cms/storage"
            - "/etc/localtime:/etc/localtime:ro"

    mongodb:
        image: mongo
        networks:
            - n-hashbrown
        restart: unless-stopped
        volumes:
            - "v-hashbrown-mongodb:/data/db"
            - "v-hashbrown-storage:/opt/hashbrown-cms/storage"
            - "/etc/localtime:/etc/localtime:ro"
